name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test the latest version of Node.js plus the last two LTS versions.
        node-version:
          - "*"
          - lts/*
          - lts/-1

    steps:
    - uses: actions/checkout@v3
    - name: Use node version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run:  npm ci

    - name: Tests
      run:  npm test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "*"
        check-latest: true
    - run:  npm ci

    - name: Linter
      run:  npm run lint

  browser-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "*"
        check-latest: true
    - run:  npm ci

    - name: Adding playwright
      run: npm install --no-save --no-package-lock playwright

    - name: Build local
      run: gulp local

    - name: Validate the browser can import TypeScript
      run: gulp test-browser-integration

  misc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "*"
        check-latest: true
    - run:  npm ci

    - name: Build scripts
      run: gulp scripts

    - name: ESLint tests
      run: gulp run-eslint-rules-tests
