name: Publish Nightly

on:
  schedule:
    - cron:  '0 7 * * *'
  # enable users to manually trigger with workflow_dispatch
  workflow_dispatch: {}
  repository_dispatch:
    types: publish-nightly

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/TypeScript'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        # Use NODE_AUTH_TOKEN environment variable to authenticate to this registry.
        registry-url: https://registry.npmjs.org/
    - name: Setup and publish nightly
      run: |
        npm whoami
        npm ci
        gulp configure-nightly
        gulp LKG
        gulp runtests-parallel
        gulp clean
        npm publish --tag next
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
