name: Create Releasable Package Drop

on:
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: npm install and test
      run: |
        npm ci
        npm test
    - name: Adding playwright
      run: npm install --no-save --no-package-lock playwright
    - name: Validate the browser can import TypeScript
      run: gulp test-browser-integration
    - name: LKG, clean, and pack
      run: |
        gulp LKG
        gulp clean
        npm pack ./
        mv typescript-*.tgz typescript.tgz
    - name: Upload built tarfile
      uses: actions/upload-artifact@v3
      with:
        name: tgz
        path: typescript.tgz
