name: Update LKG

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3

    - name: Configure Git and Update LKG
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
        npm ci
        gulp LKG
        npm test
        git diff
        git add ./lib
        git commit -m "Update LKG"
        git push
